### ISSUE TITLE
Consider to use the new multi select widget instead of preview

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-sublime-importer#10]
Testing: Microsoft/vscode#46578

With the introduction of the multi-select picker from @chrmarti I wonder if the importer could just be a small wizard where you first pick a folder (preselected with the default location) and then in a second step you see a multi-select list where you can pick each setting.

I think the current HTML rendering is not providing a lot of value over a simple picker.

![image](https://user-images.githubusercontent.com/900690/37961038-7e22a4a6-31b7-11e8-8a2e-68dd3c57f2df.png)

/cc @sandy081

**Comment by tsalinger** [comment]
great idea, thanks
