### ISSUE TITLE
workbench.editor.enablePreview not signaled as getting overwritten

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-sublime-importer#11]
Testing: https://github.com/Microsoft/vscode/issues/46578

* import sublime settings that contain `preview_on_click` setting
* have this setting also defined in user settings

=> the importer does not signal that the setting will be overwritten:

![image](https://user-images.githubusercontent.com/900690/37961238-0b5cfb00-31b8-11e8-8496-e7d51eb298d5.png)

**Comment by tsalinger** [comment]
Fixed in the latest commits, thx.
