### ISSUE TITLE
hot_exit import issues

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-sublime-importer#15]
https://github.com/Microsoft/vscode/issues/46578

If hot_exit is already set to `"files.hotExit": "onExitAndWindowClose"`, using the importer could make things less like sublime:

![image](https://user-images.githubusercontent.com/2193314/37972176-91698ad2-318c-11e8-844e-d2eccd928fda.png)

**Comment by sandy081** [comment]
@Tyriar What is the value that maps Sublime to VS Code?

**Comment by Tyriar** [comment]
@sandy081 actually refreshing my mind of how Sublime works I think onExit is the right import, I think I was confusing it with Atom.
