### ISSUE TITLE
word_wrap import issues

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-sublime-importer#17]
Microsoft/vscode#46578

![image](https://user-images.githubusercontent.com/2193314/37972854-18dcd91e-318e-11e8-8531-804f58c8964c.png)

**Comment by tsalinger** [comment]
fixed by https://github.com/Microsoft/vscode-sublime-keybindings/commit/cda3993d3fc8ae7535055e49cb94a56a3c1843d3
