### ISSUE TITLE
find_selected_text imports wrong value

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-sublime-importer#19]
Microsoft/vscode#46578

Hitting import on this:

![image](https://user-images.githubusercontent.com/2193314/37973416-43e492a4-318f-11e8-93ee-361b6cd0b597.png)

Results in:

```
  "editor.find.seedSearchStringFromSelection": true,
  "editor.fontSize": "11"
```

**Comment by sandy081** [comment]
Looks like false values are imported as true. There is a general issue #27 created for it. Hence making it a duplicate.
