### ISSUE TITLE
Show preview of settings before they imported

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-sublime-importer#2]
From @geekykaran

"I restarted a couple of times after I sent you the last message. When I tried right now, it showed me the prompt 👍🏻 my font size in Code changed after that so I'm guessing it did import something. It'd be nice if it showed what exactly is being imported and give the option to not import parts of the settings maybe :) Currently it just says two global settings found."

**Concept:**
Open a diff editor with the newly added settings, and allow the user to either confirm of reject all of the new settings before they get stored.

**Comment by auchenberg** [comment]
More "It would be nice to have more visibility into what exactly was imported. I can't remember which settings I already had configured for Code vs what was auto magically set by the plugin. Perhaps a modal, listing the setting about to take place and an option to chose some instead of all settings." from twitter.com/akras14

**Comment by tsalinger** [comment]
This has been implemented in the latest version.

**Comment by auchenberg** [comment]
Yay
